// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ComponentsVSExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "ComponentsVSExtension.bbd916ae-c9ee-4dfb-bbba-dbad292691eb";
        public const string Name = "ComponentsVSExtension";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Scott Haney";
        public const string Tags = "";
    }
}
