// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ComponentsVSExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "ComponentsVSExtension.9a385a0d-b057-4d91-8122-a6449997ab9b";
        public const string Name = "ComponentsVSExtension";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
