// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TagsVSExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "Maestro.TagsVSExtension";
        public const string Name = "Maestro.TagsVSExtension";
        public const string Description = @"Tool that creates links to files when they are dragged and dropped under any subfolder of a folder named '__Tags'. This allows for a tag based organization of files in solution explorer rather than the hierarchy based organization that is typically used.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Scott Haney";
        public const string Tags = "Software Design";
    }
}
