// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TagsVSExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "Maestro.SolutionExplorer++";
        public const string Name = "SolutionExplorer++";
        public const string Description = @"Puts files that are frequently modified together near each other in solution explorerPuts files that are frequently modified together near each other in solution explorer";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "Scott Haney";
        public const string Tags = "Software Design";
    }
}
